{
 "title": "Nextcloud Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "1111111111" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   { "name": "networkdeviceexclusion", "query": "(veth|docker|br).*" }
  ]
 },
 "panels": [
  {
   "title": "Node Quick",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{instance=\"$node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$node\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  { "title": "Nextcloud Quick", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total File Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_files_total" }
   ]
  },
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_database_size_bytes" }
   ]
  },
  {
   "title": "# of apps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_apps_installed_total" }
   ]
  },
  {
   "title": "App Updates Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nextcloud_apps_updates_available_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auth Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(nextcloud_auth_errors_total[1h])"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_system_info" }
   ]
  },
  {
   "title": "PHP Max Memory Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nextcloud_php_memory_limit_bytes"
    }
   ]
  },
  {
   "title": "PHP Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nextcloud_php_info" }
   ]
  },
  {
   "title": "PHP Max Upload Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nextcloud_php_upload_max_size_bytes"
    }
   ]
  },
  {
   "title": "Node Resource Consumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"nice\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"softirq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"steal\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Idle - Waiting for something to happen"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"} - node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"} - node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"} - node_memory_Slab_bytes{instance=\"$node\",job=\"$job\"} - node_memory_PageTables_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapCached_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\",job=\"$job\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "Hardware temperature monitor",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "node_hwmon_temp_crit_celsius{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$node\", job=\"$job\", device!~\"$networkdeviceexclusion\"}[$__rate_interval]) * 8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\", job=\"$job\", device!~\"$networkdeviceexclusion\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"$node\",job=\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Node Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk IOps",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Reads completed"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Writes completed"
      }
     ]
    },
    {
     "title": "I/O Usage Read / Write",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Successfully read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Successfully written bytes"
      }
     ]
    },
    {
     "title": "I/O Utilization",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=\"$node\",job=\"$job\",device=~\"$diskdevices\"} [$__rate_interval])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "timeseries",
     "description": "The number of bytes read from or written to the device per second",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Written bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Nextcloud Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shares by Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 13 },
     "targets": [
      { "expr": "nextcloud_shares_total", "legendFormat": "{{type}}" }
     ]
    }
   ]
  },
  {
   "title": "Caddy Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Per Second Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "rate(caddy_http_requests_total[$__rate_interval])",
       "legendFormat": "Total requests"
      },
      {
       "expr": "rate(caddy_http_request_errors_total[$__rate_interval])",
       "legendFormat": "Total errors"
      }
     ]
    },
    {
     "title": "Rate at which Latency threshold of 100ms is being exceeded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "sum(rate(caddy_http_request_duration_seconds_count[$__rate_interval])) by (handler)\n-\nsum(rate(caddy_http_request_duration_seconds_bucket{le=\"0.1\"}[$__rate_interval])) by (handler)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}