name: Build Nextcloud Image

on:
  pull_request:
    branches: ["main"]
    paths:
      - "images/nextcloud/**"
  workflow_dispatch:

env:
  IMAGE_NAME: "nextcloud"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Nextcloud app compatibilty
        run: |
          tools/nextcloud_check_app_compatibility.sh \
            images/nextcloud/Dockerfile \
            "calendar contacts facerecognition memories notify_push previewgenerator recognize tasks"

      - name: Build the Docker image
        run: |
          cd images/nextcloud
          docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:$(date +%s)
