name: Build Nextcloud Image

on:
  pull_request:
    branches: ["main"]
    paths:
      - "images/nextcloud/**"
  workflow_dispatch:

env:
  IMAGE_NAME: "nextcloud"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Nextcloud app compatibilty
      - uses: actions/checkout@v3
        run: |
          tools/nextcloud_check_app_compatibility.sh \
            images/nextcloud/Dockerfile \
            "calendar contacts facerecognition memories notify_push previewgenerator recognize tasks twofactor_totp"

      - name: Build the Docker image
      - uses: actions/checkout@v3
        run: |
          cd images/nextcloud
          docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:$(date +%s)
