name: Publish Nextcloud image

on:
  workflow_dispatch:
      
env:
  IMAGE_NAME: "nextcloud"

jobs:
  push_to_registry:
    name: Push Nextcloud image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.url=${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}
            org.opencontainers.image.documentation=${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}
            org.opencontainers.image.source=${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}
            org.opencontainers.image.licenses=Apache-2.0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./images/nextcloud
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
